language: swift
osx_image: xcode10
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

    - WORKSPACE=GoogleMaps.xcworkspace

    - DIRECTIONS_IOS_FRAMEWORK_SCHEME="GoogleMapsDirections iOS"
    - DIRECTIONS_MACOS_FRAMEWORK_SCHEME="GoogleMapsDirections macOS"
    - DIRECTIONS_TVOS_FRAMEWORK_SCHEME="GoogleMapsDirections tvOS"
    - DIRECTIONS_WATCHOS_FRAMEWORK_SCHEME="GoogleMapsDirections watchOS"

    - PLACES_IOS_FRAMEWORK_SCHEME="GooglePlaces iOS"
    - PLACES_MACOS_FRAMEWORK_SCHEME="GooglePlaces macOS"
    - PLACES_TVOS_FRAMEWORK_SCHEME="GooglePlaces tvOS"
    - PLACES_WATCHOS_FRAMEWORK_SCHEME="GooglePlaces watchOS"

    - EXAMPLE_SCHEME="iOS Example"

  matrix:
    # GoogleMapsDirections
    ## iOS
    - DESTINATION="OS=12.0,name=iPhone XS Max"                 SCHEME="$DIRECTIONS_IOS_FRAMEWORK_SCHEME"        RUN_TESTS="YES"
    # - DESTINATION="OS=11.4,name=iPhone X"                      SCHEME="$DIRECTIONS_IOS_FRAMEWORK_SCHEME"        RUN_TESTS="YES"
    # - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"               SCHEME="$DIRECTIONS_IOS_FRAMEWORK_SCHEME"        RUN_TESTS="YES"
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"                 SCHEME="$DIRECTIONS_IOS_FRAMEWORK_SCHEME"        RUN_TESTS="YES"
         
    ## macOS         
    - DESTINATION="arch=x86_64"                                SCHEME="$DIRECTIONS_MACOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES"
         
    ## tvOS         
    - DESTINATION="OS=12.0,name=Apple TV 4K"                   SCHEME="$DIRECTIONS_TVOS_FRAMEWORK_SCHEME"       RUN_TESTS="YES"
    - DESTINATION="OS=11.4,name=Apple TV 4K"                   SCHEME="$DIRECTIONS_TVOS_FRAMEWORK_SCHEME"       RUN_TESTS="YES"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"                SCHEME="$DIRECTIONS_TVOS_FRAMEWORK_SCHEME"       RUN_TESTS="YES"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"                 SCHEME="$DIRECTIONS_TVOS_FRAMEWORK_SCHEME"       RUN_TESTS="YES"
    
    ## watchOS
    - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"    SCHEME="$DIRECTIONS_WATCHOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"
    - DESTINATION="OS=4.2,name=Apple Watch Series 3 - 42mm"    SCHEME="$DIRECTIONS_WATCHOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"
    - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm"    SCHEME="$DIRECTIONS_WATCHOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm"             SCHEME="$DIRECTIONS_WATCHOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO" 

    # GooglePlaces
    ## iOS
    - DESTINATION="OS=12.0,name=iPhone XS Max"                 SCHEME="$PLACES_IOS_FRAMEWORK_SCHEME"            RUN_TESTS="YES"
    # - DESTINATION="OS=11.4,name=iPhone X"                      SCHEME="$PLACES_IOS_FRAMEWORK_SCHEME"            RUN_TESTS="YES"
    # - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"               SCHEME="$PLACES_IOS_FRAMEWORK_SCHEME"            RUN_TESTS="YES"
    - DESTINATION="OS=9.3,name=iPhone 6s Plus"                 SCHEME="$PLACES_IOS_FRAMEWORK_SCHEME"            RUN_TESTS="YES"
             
    ## macOS             
    - DESTINATION="arch=x86_64"                                SCHEME="$PLACES_MACOS_FRAMEWORK_SCHEME"          RUN_TESTS="YES"
             
    ## tvOS             
    - DESTINATION="OS=12.0,name=Apple TV 4K"                   SCHEME="$PLACES_TVOS_FRAMEWORK_SCHEME"           RUN_TESTS="YES"
    - DESTINATION="OS=11.4,name=Apple TV 4K"                   SCHEME="$PLACES_TVOS_FRAMEWORK_SCHEME"           RUN_TESTS="YES"
    - DESTINATION="OS=10.2,name=Apple TV 1080p"                SCHEME="$PLACES_TVOS_FRAMEWORK_SCHEME"           RUN_TESTS="YES"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"                 SCHEME="$PLACES_TVOS_FRAMEWORK_SCHEME"           RUN_TESTS="YES"
                 
    ## watchOS    
    - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"    SCHEME="$PLACES_WATCHOS_FRAMEWORK_SCHEME"        RUN_TESTS="NO"
    - DESTINATION="OS=4.2,name=Apple Watch Series 3 - 42mm"    SCHEME="$PLACES_WATCHOS_FRAMEWORK_SCHEME"        RUN_TESTS="NO"
    - DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm"    SCHEME="$PLACES_WATCHOS_FRAMEWORK_SCHEME"        RUN_TESTS="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm"             SCHEME="$PLACES_WATCHOS_FRAMEWORK_SCHEME"        RUN_TESTS="NO" 
   
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -showdestinations -workspace "$WORKSPACE" -scheme "$SCHEME"

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    else
      xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug | xcpretty;
    fi

  # Build Framework in Release
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release | xcpretty;
